swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: '1.0'
  title: CDS Hooks REST API
host: cds-service-example.herokuapp.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /cds-services:
    get:
      description: Get a description of all CDS services offered by this CDS Provider
      responses:
        200:
          description: Success (includes CDS service metadata)
          schema:
            $ref: '#/definitions/CDS%20Service%20Information'

  /cds-services/{id}:
    post:
      description: Invoke a CDS service offered by this CDS Provider
      parameters:
        - name: id
          in: path
          description: The id of this CDS service
          required: true
          type: string
        - name: request
          in: body
          description: Body of CDS service request
          required: true
          schema:
            $ref: '#/definitions/CDS%20Request'
      responses:
        200:
          description: Success (includes CDS Cards)
          schema:
            $ref: '#/definitions/CDS%20Response'

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  CDS Service Information:
    type: object
    properties:
      services:
        type: array
        items:
           $ref: '#/definitions/CDS%20Service'

  CDS Service:
    type: object
    required:
      - id
      - hook
      - description
    properties:
      id:
        type: string
        description: short id for this service, unique with the CDS Provider (will be used in URL paths)
      hook:
        type: string
        description: The hook this service should be invoked on.
      title:
        type: string
        description: Human-readable name for the CDS Service (e.g. "CMS Drug Pricing Service")
      description:
        type: string
        description: Longer-form description of what the service offers
      prefetch:
        $ref: '#/definitions/Prefetch'

  CDS Request:
    type: object
    required:
      - hook
      - hookInstance
      - context
    properties:
      hook:
        type: string
        description: The hook that triggered this CDS Service call.
      hookInstance:
        type: string
        format: uuid
      fhirServer:
        type: string
        format: url
      fhirAuthorization:
        $ref: '#/definitions/FHIR%20Authorization'
      context:
        type: object
      prefetch:
        type: object

  FHIR Authorization:
    type: object
    required:
      - access_token
      - token_type
      - expires_in
      - scope
      - subject
    properties:
      access_token:
        type: string
      token_type:
        type: string
        enum:
          - Bearer
      expires_in:
        type: integer
      scope:
        type: string
      subject:
        type: string

  CDS Response:
    type: object
    required:
      - cards
    properties:
      cards:
        type: array
        items:
          $ref: '#/definitions/Card'

  Card:
    type: object
    required:
      - summary
      - indicator
      - source
    properties:
      summary:
        type: string
      detail:
        type: string
      indicator:
        type: string
        enum:
          - info
          - warning
          - critical
      source:
        $ref: '#/definitions/Source'
      suggestions:
        type: array
        items:
          $ref: '#/definitions/Suggestion'
      selectionBehavior:
        type: string
        enum:
          - at-most-one
      links:
        type: array
        items:
          $ref: '#/definitions/Link'

  Source:
    type: object
    required:
      - label
    properties:
      label:
        type: string
      url:
        type: string
        format: url
      icon:
        type: string
        format: url

  Link:
    type: object
    required:
      - label
      - url
      - type
    properties:
      label:
        type: string
      url:
        type: string
        format: url
      type:
        type: string
        enum:
          - absolute
          - smart
      appContext:
        type: string

  Suggestion:
    type: object
    required:
      - label
    properties:
      label:
        type: string
      uuid:
        type: string
        format: uuid
      actions:
        type: array
        items:
          $ref: '#/definitions/Action'

  Action:
    type: object
    required:
      - type
      - description
    properties:
      type:
        type: string
        enum:
          - create
          - update
          - delete
      description:
        type: string
      resource:
        type: object

  Prefetch:
    type: object
    description: queries that the CDS Service would like the CDS Client to execute before every call
    additionalProperties:
      type: string
